version: 2
updates:
  # 1. Revisa actualizaciones de paquetes npm (tu código principal)
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily" # Busca actualizaciones cada día
    open-pull-requests-limit: 10 # Máximo 10 PRs abiertos a la vez
    labels:
      - "dependencies"
      - "javascript"

  # 2. Revisa actualizaciones de las propias GitHub Actions que usas
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # Las acciones cambian menos, una vez por semana basta
