version: 2
updates:
  # Actualizaciones para npm (JavaScript/TypeScript)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"

  # Actualizaciones para las propias GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
