version: 2
updates:
  # Configuración para las dependencias de npm (JavaScript)
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    # Opcional: limita el número de PRs abiertos a la vez para no saturarte
    open-pull-requests-limit: 10

  # También revisará si hay actualizaciones para tus GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
